version: '3.10'



services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    command: >
      sh -c "python ./src/manage.py wait_for_db &&
             python ./src/manage.py migrate &&
             python ./src/manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15.3-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/config/db.env
    ports:
      - "5432:5432"

volumes:
  postgres_data: